# Generated by Django 6.0.7 on 2026-07-25 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrmTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'CRM/tool',
                'verbose_name_plural': 'CRM/tools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'work styles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('linkedin_url', models.URLField()),
                ('current_company_name', models.CharField(max_length=200)),
                ('current_title', models.CharField(choices=[('SDR', 'SDR'), ('BDR', 'BDR'), ('AE', 'AE'), ('Sales Manager', 'Sales Manager'), ('Other', 'Other')], max_length=20)),
                ('years_experience', models.PositiveIntegerField()),
                ('quota_attainment_pct', models.PositiveIntegerField(help_text='% to quota, last period')),
                ('base_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('ote', models.PositiveIntegerField(blank=True, null=True, verbose_name='current OTE')),
                ('desired_ote', models.PositiveIntegerField()),
                ('open_to_relocation', models.BooleanField()),
                ('awards', models.TextField(blank=True)),
                ('resume', models.FileField(upload_to='resumes/%Y/%m/')),
                ('status', models.CharField(choices=[('new', 'New'), ('screening', 'Screening'), ('active', 'Active'), ('placed', 'Placed'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('ranking_score', models.PositiveSmallIntegerField(blank=True, help_text='0-100, higher is better', null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crm_tools', models.ManyToManyField(blank=True, related_name='candidates', to='candidates.crmtool')),
                ('industries', models.ManyToManyField(blank=True, related_name='candidates', to='candidates.industry')),
                ('work_styles', models.ManyToManyField(blank=True, related_name='candidates', to='candidates.workstyle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Role being hired for, e.g. "Senior AE"', max_length=200)),
                ('comp_min', models.PositiveIntegerField(blank=True, null=True)),
                ('comp_max', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('closed', 'Closed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='candidates.company')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='candidates.industry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('submitted', 'Submitted'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('placed', 'Placed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('fit_score', models.PositiveSmallIntegerField(blank=True, help_text='0-100, higher is a better fit for this requisition', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='candidates.candidate')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='candidates.requisition')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'requisition'), name='unique_candidate_requisition')],
            },
        ),
    ]
