# Generated by Django 6.0.7 on 2026-07-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_seed_lookups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_title',
            field=models.CharField(blank=True, choices=[('SDR', 'SDR'), ('BDR', 'BDR'), ('AE', 'AE'), ('Sales Manager', 'Sales Manager'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='quota_attainment_pct',
            field=models.PositiveIntegerField(blank=True, help_text='% to quota, last period', null=True),
        ),
    ]
