# Generated by Django 6.0.7 on 2026-07-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidate_current_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='requisition',
            name='role_type',
            field=models.CharField(blank=True, choices=[('SDR', 'SDR'), ('BDR', 'BDR'), ('AE', 'AE'), ('Sales Manager', 'Sales Manager'), ('Other', 'Other')], help_text="Normalised role, matched against a candidate's current title", max_length=20),
        ),
        migrations.AddField(
            model_name='requisition',
            name='timeline',
            field=models.CharField(blank=True, choices=[('ASAP', 'ASAP'), ('Within 30 days', 'Within 30 days'), ('This quarter', 'This quarter'), ('Just exploring', 'Just exploring')], max_length=20),
        ),
    ]
