# Generated by Django 6.0.7 on 2026-07-29 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_recruiters_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ranking_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ranking_model_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ResumeExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('raw_text', models.TextField(blank=True)),
                ('extraction_error', models.TextField(blank=True)),
                ('extracted_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_extraction', to='candidates.candidate')),
            ],
        ),
    ]
