# Generated by Django 6.0.7 on 2026-07-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_ranking_computed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ranking_notes',
            field=models.TextField(blank=True, help_text='AI-generated summary/flags from the last ranking run.'),
        ),
    ]
