# Generated by Django 6.0.7 on 2026-07-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_ranking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='promotion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='promotion_readiness',
            field=models.CharField(blank=True, choices=[('not_yet', 'Not Yet'), ('developing', 'Developing'), ('ready', 'Ready'), ('not_applicable', 'N/A')], max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ranking_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
