# Generated by Django 6.0.7 on 2026-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidate_promotion_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='base_salary',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='desired_ote',
            field=models.CharField(choices=[('$50k-$80k', '$50k – $80k'), ('$80k-$110k', '$80k – $110k'), ('$110k-$140k', '$110k – $140k'), ('$140k-$250k', '$140k – $250k'), ('$250k+', '$250k+')], max_length=20),
        ),
    ]
