# Generated by Django 6.0.7 on 2026-08-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_remove_candidate_base_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='booking_invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='nurture_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pass_fail',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=4),
        ),
    ]
