# Generated by Django 6.0.7 on 2026-08-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_candidate_automation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='promotion_notes',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='promotion_readiness',
        ),
    ]
