# Generated by Django 6.0.7 on 2026-08-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_candidate_manual_ranked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ranking_recommended_title',
            field=models.CharField(blank=True, choices=[('SDR', 'SDR'), ('BDR', 'BDR'), ('AE', 'AE'), ('Sales Manager', 'Sales Manager'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='screening_title',
            field=models.CharField(blank=True, choices=[('SDR', 'SDR'), ('BDR', 'BDR'), ('AE', 'AE'), ('Sales Manager', 'Sales Manager'), ('Other', 'Other')], max_length=20),
        ),
    ]
