# Generated by Django 6.0.7 on 2026-08-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_candidate_screening_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAE',
            fields=[
            ],
            options={
                'verbose_name': 'AE',
                'verbose_name_plural': "AE's",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('candidates.candidate',),
        ),
        migrations.CreateModel(
            name='CandidateRejected',
            fields=[
            ],
            options={
                'verbose_name': 'Rejected Candidate',
                'verbose_name_plural': 'Rejected',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('candidates.candidate',),
        ),
        migrations.CreateModel(
            name='CandidateSalesManager',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Manager',
                'verbose_name_plural': 'Sales Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('candidates.candidate',),
        ),
        migrations.CreateModel(
            name='CandidateSDRBDR',
            fields=[
            ],
            options={
                'verbose_name': 'SDR/BDR',
                'verbose_name_plural': 'SDR/BDRs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('candidates.candidate',),
        ),
    ]
