# Generated by Django 6.0.7 on 2026-08-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_candidate_state_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('form', 'Public form'), ('linkedin', 'LinkedIn sourcing')], default='form', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='desired_ote',
            field=models.CharField(blank=True, choices=[('$50k-$80k', '$50k – $80k'), ('$80k-$110k', '$80k – $110k'), ('$110k-$140k', '$110k – $140k'), ('$140k-$250k', '$140k – $250k'), ('$250k+', '$250k+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='open_to_relocation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state_province',
            field=models.CharField(blank=True, choices=[('United States', [('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('District of Columbia', 'District of Columbia'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')]), ('Canada', [('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Northwest Territories', 'Northwest Territories'), ('Nova Scotia', 'Nova Scotia'), ('Nunavut', 'Nunavut'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan'), ('Yukon', 'Yukon')])], max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
