# Generated by Django 6.0.7 on 2026-08-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_candidate_source_alter_candidate_desired_ote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('rejected', 'Rejected')], default='active', max_length=10),
        ),
    ]
