# Generated by Django 6.0.7 on 2026-08-26 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_requisition_job_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('audience_type', models.CharField(choices=[('candidate', 'Candidate sourcing'), ('contact', 'Business development')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='candidates.requisition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='1-based position in the sequence.')),
                ('step_type', models.CharField(choices=[('email', 'Email'), ('linkedin_inmail', 'LinkedIn InMail'), ('linkedin_connection', 'LinkedIn connection request'), ('phone_call', 'Phone call'), ('general_task', 'General task')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Days after the previous step (or enrollment, for step 1) before this step is due. 0 = immediately.')),
                ('send_window_start', models.TimeField(blank=True, null=True)),
                ('send_window_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='candidates.campaign')),
            ],
            options={
                'ordering': ['campaign', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, help_text='Job title at this company, e.g. "VP Sales" -- free text, unrelated to TITLE_CHOICES.', max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='candidates.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('removed', 'Removed')], default='active', max_length=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='candidates.campaign')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='candidates.candidate')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='candidates.contact')),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='candidates.campaignstep')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_step_executions', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='candidates.campaignenrollment')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaignstep',
            constraint=models.UniqueConstraint(fields=('campaign', 'order'), name='unique_campaign_step_order'),
        ),
        migrations.AddConstraint(
            model_name='campaignenrollment',
            constraint=models.UniqueConstraint(fields=('campaign', 'candidate'), name='unique_campaign_candidate'),
        ),
        migrations.AddConstraint(
            model_name='campaignenrollment',
            constraint=models.UniqueConstraint(fields=('campaign', 'contact'), name='unique_campaign_contact'),
        ),
        migrations.AddConstraint(
            model_name='campaignenrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('candidate__isnull', False), ('contact__isnull', True)), models.Q(('candidate__isnull', True), ('contact__isnull', False)), _connector='OR'), name='campaign_enrollment_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='stepexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('enrollment',), name='unique_pending_step_execution_per_enrollment'),
        ),
    ]
