"""
Django settings for salesfloor project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file explicitly (must be after BASE_DIR definition)
load_dotenv(BASE_DIR / '.env')


# Local dev falls back to the checked-in insecure key and DEBUG=True;
# Render (or any real deployment) must set these via environment variables.
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-^xj7#pgge%k!0@m$9*=+5o6c2dl!3#=^d6t)wg2980e8voe5gz'
)

DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]


# Application definition

INSTALLED_APPS = [
    # Points the default admin site at SalesFloorAdminSite (see
    # candidates/admin_config.py, candidates/admin_site.py) so the sidebar
    # can be reordered/filtered without touching any @admin.register(...) call.
    'candidates.admin_config.CandidatesAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'candidates',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# The public intake form lives on a different origin (GitHub Pages /
# thesalesfloor.biz) than this API, so it needs CORS allowed explicitly.
# The localhost entries are for the static site served locally during
# development (e.g. `py -m http.server 8080`), not this API's own origin.
CORS_ALLOWED_ORIGINS = [
    'https://thesalesfloor.biz',
    'https://www.thesalesfloor.biz',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
]

ROOT_URLCONF = 'salesfloor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Project-level overrides (e.g. templates/admin/index.html, which adds
        # the QA Review Queue link) -- DIRS is checked before each app's own
        # templates/, which is what lets {% extends "admin/index.html" %} in
        # our override reach django.contrib.admin's original version instead
        # of recursing into itself.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'salesfloor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Local dev uses SQLite by default. Render sets DATABASE_URL (Postgres),
# which takes over automatically when present.

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Resume uploads. MEDIA_ROOT defaults to a local folder for dev; on Render
# this must be set to the mounted persistent disk path (e.g. /var/data/media)
# via the MEDIA_ROOT env var, or uploaded resumes are lost on every redeploy.
# MEDIA_URL is backed by the staff-only serve_media view (see salesfloor/urls.py),
# not by a static file route -- resumes are candidate PII.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media'))

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AI resume ranking (candidates.ai). No local-dev default for the key --
# extract_structured() raises AIConfigurationError if it's unset, which
# callers (management commands, admin actions) catch and skip/report rather
# than crash. AI_MODEL is swappable via env var alone, no deploy needed.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
AI_MODEL = os.environ.get('AI_MODEL', 'claude-sonnet-5')

# Shared secret the n8n automation workflow sends as X-Automation-Key (see
# candidates/automation_views.py). No local-dev default -- blank means every
# automation request is rejected, same failure-closed pattern as
# ANTHROPIC_API_KEY.
AUTOMATION_API_KEY = os.environ.get('AUTOMATION_API_KEY', '')

# Public base URL of this site, used to build links (e.g. the QA review page
# link in daily_report) that go into outbound emails. Deliberately not
# request.build_absolute_uri() -- that would reflect whatever host called the
# automation endpoint (n8n's own network path), not the URL a human should
# actually click.
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://localhost:8000')

# Static Calendly scheduling page candidates are invited to book on (see
# candidates/qa_views.send_invite). No Calendly API/OAuth is used here --
# Calendly's own hosted page shows the candidate available times.
CALENDLY_SCHEDULING_URL = os.environ.get('CALENDLY_SCHEDULING_URL', '')

# n8n webhook Django calls (from candidates/qa_views.send_invite) to trigger
# the candidate's Calendly invite email. Authenticated with the same
# AUTOMATION_API_KEY used for the inbound n8n -> Django direction, since
# whoever holds that key can already read/write every /api/automation/
# endpoint -- a second secret here wouldn't buy any real isolation.
N8N_INVITE_WEBHOOK_URL = os.environ.get('N8N_INVITE_WEBHOOK_URL', '')

# The only login form this project has is the admin's. qa_views' pages use
# @login_required (stacked ahead of @staff_member_required, see
# qa_reviewer_required), which without this would send anonymous users to
# Django's default /accounts/login/ -- a URL nothing serves here.
LOGIN_URL = '/admin/login/'

# Django's default logging only prints request tracebacks to console when
# DEBUG=True (otherwise it tries to email an unconfigured admin and the
# error goes nowhere visible) -- send them to console/Render logs instead.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'INFO'},
        # candidates.automation_views logs the real exception on a per-candidate
        # ranking failure, since the JSON response only reports a count -- n8n
        # has no UI to surface it, so Render's console log is the only place
        # to see why a batch reported failures.
        'candidates': {'handlers': ['console'], 'level': 'INFO'},
    },
}
